/**
 * AISolutionsOS — data.js
 * Single source of truth for all site content.
 * Exposed globally as window.AISO so every page can render from it.
 */
(function () {
  'use strict';

  /* ─── Tools (Build Studio) ──────────────────────────────── */
  const tools = [
    {
      id: 'prompt-to-product',
      title: 'Prompt-to-Product Packager',
      tagline: 'Package any prompt into a sellable product',
      desc: 'Package any prompt into a sellable product with structured metadata, pricing, and delivery copy.',
      icon: 'doc',
      status: 'live',
      category: 'Productize',
      tags: ['monetization', 'product building', 'content'],
    },
    {
      id: 'workflow-to-skill',
      title: 'Workflow-to-Skill Builder',
      tagline: 'Convert workflows into Claude skills',
      desc: 'Convert your workflows into reusable Claude skills with proper SKILL.md formatting and frontmatter.',
      icon: 'layers',
      status: 'soon',
      category: 'Build',
      tags: ['coding', 'automation'],
    },
    {
      id: 'mcp-spec-generator',
      title: 'MCP Spec Generator',
      tagline: 'Generate MCP server specs instantly',
      desc: 'Generate a complete MCP server spec — tools, resources, and schema — from a plain-language description.',
      icon: 'nodes',
      status: 'live',
      category: 'Build',
      tags: ['coding', 'automation'],
    },
    {
      id: 'cli-scaffold-studio',
      title: 'CLI Scaffold Studio',
      tagline: 'Scaffold CLI tools from descriptions',
      desc: 'Scaffold production-ready CLI tools from natural language descriptions with command trees and flags.',
      icon: 'terminal',
      status: 'soon',
      category: 'Build',
      tags: ['coding'],
    },
    {
      id: 'automation-planner',
      title: 'Automation Planner',
      tagline: 'Plan n8n/Zapier automations visually',
      desc: 'Plan and visualize n8n/Zapier automations with AI-generated logic flows and trigger maps.',
      icon: 'flow',
      status: 'soon',
      category: 'Plan',
      tags: ['automation', 'monetization'],
    },
    {
      id: 'build-audit-checker',
      title: 'Build Audit Checker',
      tagline: 'Audit your AI builds for gaps',
      desc: 'Audit your AI builds for gaps, missing components, and improvement areas with a scored checklist.',
      icon: 'check',
      status: 'live',
      category: 'Audit',
      tags: ['product building', 'research'],
    },
    {
      id: 'agent-pack-generator',
      title: 'Agent Pack Generator',
      tagline: 'Bundle agents into deployable packs',
      desc: 'Bundle multiple agents into structured, deployable agent packs with manifests and routing.',
      icon: 'shield',
      status: 'soon',
      category: 'Build',
      tags: ['coding', 'automation'],
    },
    {
      id: 'content-repurposing',
      title: 'Content Repurposing Console',
      tagline: 'Turn one piece into many assets',
      desc: 'Turn one piece of content into multiple formats and distribution assets across platforms.',
      icon: 'grid',
      status: 'soon',
      category: 'Content',
      tags: ['content', 'monetization'],
    },
  ];

  /* ─── Library assets ────────────────────────────────────── */
  const library = [
    {
      id: 'claude-code-system-prompt',
      title: 'Claude Code System Prompt',
      type: 'prompt',
      typeLabel: 'Prompt',
      desc: 'A battle-tested system prompt for running Claude Code on complex multi-file projects.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '2.1.0',
      updated: '2026-06-10',
      forWho: 'Developers running Claude Code on large codebases.',
      problem: 'Default prompting drifts on big repos — losing track of architecture and conventions.',
      inputs: 'Your repo structure and a short description of conventions.',
      output: 'A drop-in system prompt that keeps Claude anchored to your codebase.',
      setup: 'Copy the prompt into your CLAUDE.md or system prompt field. Adjust the conventions block.',
      example: 'You are working in a TypeScript monorepo. Always match the surrounding code style...',
      content: 'You are an expert software engineer working in this repository. Before editing, read the surrounding code and match its conventions exactly. Prefer minimal diffs. Never invent APIs — verify against the codebase first.',
    },
    {
      id: 'github-mcp-server',
      title: 'GitHub MCP Server',
      type: 'mcp',
      typeLabel: 'MCP Server',
      desc: 'Full GitHub integration via MCP — repos, PRs, issues, and file operations.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '1.4.2',
      updated: '2026-06-08',
      forWho: 'Anyone automating GitHub workflows from an AI agent.',
      problem: 'Manually copy-pasting between GitHub and your AI tool is slow and error-prone.',
      inputs: 'A GitHub personal access token with repo scope.',
      output: 'A running MCP server exposing repo, PR, and issue tools.',
      setup: 'Add the server to your MCP config, set GITHUB_TOKEN, and restart your client.',
      example: 'list_pull_requests(owner="acme", repo="web") → returns open PRs.',
      content: '{\n  "mcpServers": {\n    "github": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-github"],\n      "env": { "GITHUB_TOKEN": "<your-token>" }\n    }\n  }\n}',
    },
    {
      id: 'workflow-to-skill-converter',
      title: 'Workflow-to-Skill Converter',
      type: 'skill',
      typeLabel: 'Skill',
      desc: 'Convert any documented workflow into a properly structured Claude skill file.',
      status: 'draft',
      free: true,
      difficulty: 'beginner',
      useCase: 'automation',
      compat: ['claude'],
      version: '0.3.0',
      updated: '2026-06-15',
      forWho: 'Builders who keep repeating the same multi-step process.',
      problem: 'Workflows live in your head or scattered docs — not reusable by an agent.',
      inputs: 'A written description of your workflow steps.',
      output: 'A SKILL.md file with frontmatter, triggers, and instructions.',
      setup: 'Drop the generated SKILL.md into .claude/skills/<name>/.',
      example: '---\nname: weekly-report\ndescription: Generate the weekly metrics report\n---',
      content: '---\nname: your-skill\ndescription: When to use this skill\n---\n\n# Steps\n1. ...\n2. ...',
    },
    {
      id: 'ai-build-audit-checklist',
      title: 'AI Build Audit Checklist',
      type: 'checklist',
      typeLabel: 'Checklist',
      desc: 'A comprehensive checklist to audit any AI build for gaps and missing pieces.',
      status: 'tested',
      free: true,
      difficulty: 'beginner',
      useCase: 'product building',
      compat: ['claude', 'gpt'],
      version: '1.0.0',
      updated: '2026-06-01',
      forWho: 'Solopreneurs shipping AI products who want a quality bar.',
      problem: 'It is easy to ship an AI build with silent gaps — no error handling, no docs, no tests.',
      inputs: 'Your project, open in front of you.',
      output: 'A scored audit highlighting what is missing.',
      setup: 'Run through each item and mark pass/fail. Use the Build Audit Checker tool to score it.',
      example: '☐ Inputs validated  ☐ Errors handled  ☐ Docs written  ☐ Tested',
      content: '1. Inputs validated\n2. Errors handled gracefully\n3. Output format documented\n4. Compatibility stated\n5. Tested end-to-end\n6. Pricing / use-case noted',
    },
    {
      id: 'prompt-to-product-sop',
      title: 'Prompt-to-Product SOP',
      type: 'template',
      typeLabel: 'Template',
      desc: 'Step-by-step SOP for packaging a raw prompt into a productized, sellable asset.',
      status: 'tested',
      free: false,
      difficulty: 'intermediate',
      useCase: 'monetization',
      compat: ['claude', 'gpt', 'gemini'],
      version: '2.0.0',
      updated: '2026-05-28',
      forWho: 'Creators who want to sell prompts as real products.',
      problem: 'A raw prompt is not a product — it needs packaging, pricing, and delivery.',
      inputs: 'One prompt you already use and trust.',
      output: 'A complete product page outline with pricing tiers.',
      setup: 'Follow the 7 steps in order. Pair with the Prompt-to-Product Packager tool.',
      example: 'Step 1: Name the outcome. Step 2: Define the buyer...',
      content: 'Step 1 — Name the outcome\nStep 2 — Define the buyer\nStep 3 — Write the promise\nStep 4 — Package the prompt\nStep 5 — Price it\nStep 6 — Write delivery copy\nStep 7 — Ship',
    },
    {
      id: 'agent-pack-starter-kit',
      title: 'Agent Pack Starter Kit',
      type: 'template',
      typeLabel: 'Template',
      desc: 'A starter template for bundling multiple AI agents into a deployable agent pack.',
      status: 'draft',
      free: true,
      difficulty: 'advanced',
      useCase: 'coding',
      compat: ['claude'],
      version: '0.2.1',
      updated: '2026-06-16',
      forWho: 'Advanced builders shipping multi-agent systems.',
      problem: 'Multi-agent setups get messy without a clear pack structure.',
      inputs: 'A list of agents and their responsibilities.',
      output: 'A folder structure and manifest for a deployable agent pack.',
      setup: 'Clone the structure, fill in each agent definition, wire the router.',
      example: 'agents/\n  researcher.md\n  writer.md\n  editor.md\nmanifest.json',
      content: '{\n  "name": "content-pack",\n  "agents": ["researcher", "writer", "editor"],\n  "router": "orchestrator"\n}',
    },
    {
      id: 'notion-prompt-database',
      title: 'Notion Prompt Database',
      type: 'template',
      typeLabel: 'Template',
      desc: 'A ready-made Notion database for cataloging, tagging, and reusing your prompts.',
      status: 'tested',
      free: false,
      difficulty: 'beginner',
      useCase: 'content',
      compat: ['claude', 'gpt', 'gemini'],
      version: '1.2.0',
      updated: '2026-05-20',
      forWho: 'Anyone drowning in scattered prompts across tabs and notes.',
      problem: 'Good prompts get lost. There is no system to find or reuse them.',
      inputs: 'A free Notion account.',
      output: 'A structured database with tags, status, and compatibility fields.',
      setup: 'Duplicate the template into your workspace and start adding prompts.',
      example: 'Fields: Title, Type, Tool, Status, Use case, Rating',
      content: 'Duplicate the Notion template, then map your prompts into the fields.',
    },
    {
      id: 'repo-cleanup-cli',
      title: 'Repo Cleanup CLI',
      type: 'cli',
      typeLabel: 'CLI',
      desc: 'A small CLI that audits a repo for stale branches, large files, and missing docs.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '0.9.0',
      updated: '2026-06-12',
      forWho: 'Developers who want a quick repo health check.',
      problem: 'Repos accumulate cruft — stale branches, oversized files, missing READMEs.',
      inputs: 'A local git repository.',
      output: 'A printed report of issues found.',
      setup: 'npm i -g repo-cleanup, then run `repo-cleanup .` in your repo.',
      example: '$ repo-cleanup .  →  3 stale branches, 1 file > 5MB, no LICENSE',
      content: '#!/usr/bin/env node\n// scans cwd git repo and prints a health report',
    },
    {
      id: 'daily-digest-automation',
      title: 'Daily Digest Automation',
      type: 'automation',
      typeLabel: 'Automation',
      desc: 'An n8n flow that pulls your sources each morning and sends an AI-summarized digest.',
      status: 'tested',
      free: false,
      difficulty: 'intermediate',
      useCase: 'automation',
      compat: ['claude', 'gpt'],
      version: '1.1.0',
      updated: '2026-06-05',
      forWho: 'Anyone who wants a curated morning briefing, hands-off.',
      problem: 'Manually checking 10 sources every morning wastes the best hour of your day.',
      inputs: 'n8n instance, your source URLs/feeds, an LLM API key.',
      output: 'A daily summarized email or Slack message.',
      setup: 'Import the workflow JSON into n8n, set credentials, schedule it.',
      example: 'Trigger: 7am daily → Fetch sources → Summarize → Email',
      content: '{ "nodes": [ { "type": "schedule" }, { "type": "http" }, { "type": "llm" }, { "type": "email" } ] }',
    },
  ];

  /* ─── Blog posts ────────────────────────────────────────── */
  const posts = [
    {
      slug: 'prompt-to-47-dollar-product',
      title: 'How I Packaged a Prompt into a $47 Product in 48 Hours',
      tag: 'build-log',
      tagLabel: 'Build Log',
      date: '2026-06-14',
      readTime: '7 min',
      excerpt: 'A real-time case study walking through every step of turning a raw prompt into a productized, shippable asset with pricing, copy, and delivery.',
      body: [
        'I had a prompt I used every day to turn meeting notes into action items. It was good. But a good prompt is not a product.',
        'Over 48 hours I packaged it: named the outcome, defined the buyer, wrote the promise, set a price, and built a one-page delivery. Here is exactly what I did.',
        'Step one was naming the outcome, not the mechanism. Nobody buys "a prompt." They buy "meeting notes to action items in 30 seconds." That reframe changed everything about the copy.',
        'By hour 48 it was live at $47. The lesson: the prompt was 10% of the work. Packaging was the product.',
      ],
    },
    {
      slug: 'mcp-server-setup-guide',
      title: 'The MCP Server Setup Guide Nobody Wrote',
      tag: 'tutorial',
      tagLabel: 'Tutorial',
      date: '2026-06-09',
      readTime: '11 min',
      excerpt: 'Everything you need to know to set up, configure, and connect an MCP server to Claude — without the gaps the official docs leave behind.',
      body: [
        'MCP is powerful but the setup docs assume a lot. This guide fills the gaps that trip up most first-timers.',
        'We cover the config file location, environment variables, the most common connection errors, and how to verify the server is actually exposing its tools.',
        'The single biggest gotcha: restarting the client. Config changes do not hot-reload. Restart fully.',
        'By the end you will have a working server and know how to debug the next one yourself.',
      ],
    },
    {
      slug: 'claude-skills-vs-plugins',
      title: 'Claude Skills vs Plugins: A Practical Breakdown',
      tag: 'deep-dive',
      tagLabel: 'Deep Dive',
      date: '2026-06-03',
      readTime: '9 min',
      excerpt: 'An honest comparison of Claude skills and plugins — what they do, where they overlap, and when to use each one in your AI system stack.',
      body: [
        'Skills and plugins solve related but different problems. Confusing them leads to over-engineering.',
        'A skill is reusable knowledge and instructions. A plugin bundles skills, commands, and configuration for distribution.',
        'Rule of thumb: start with a skill. Reach for a plugin only when you need to package and share several skills together.',
        'We walk through three real scenarios and pick the right tool for each.',
      ],
    },
    {
      slug: 'tested-this-tool-n8n',
      title: 'I Tested n8n for AI Automation for 30 Days',
      tag: 'tested',
      tagLabel: 'I Tested This',
      date: '2026-05-26',
      readTime: '8 min',
      excerpt: 'Thirty days of building AI automations in n8n — what worked, what broke, and whether it is worth replacing Zapier for solo builders.',
      body: [
        'I moved my automations from Zapier to n8n for a month. Here is the honest report.',
        'The wins: self-hosting, no per-task pricing, and real branching logic. The pain: a steeper learning curve and occasional node quirks.',
        'For high-volume AI workflows, n8n paid for itself in week one. For simple two-step zaps, it was overkill.',
        'Verdict: worth it if you are running more than a handful of automations.',
      ],
    },
    {
      slug: 'turn-this-into-a-product',
      title: 'Turn This Into a Product: The Repurposing Playbook',
      tag: 'build-log',
      tagLabel: 'Build Log',
      date: '2026-05-18',
      readTime: '6 min',
      excerpt: 'A repeatable playbook for spotting which of your workflows can become a sellable product — and which should stay internal tools.',
      body: [
        'Not every workflow should be a product. This playbook helps you tell the difference.',
        'The test: does it solve an expensive, repeated, painful problem for someone other than you? If yes, productize. If no, keep it as an internal tool.',
        'We score three of my own workflows against the test and decide which one ships.',
      ],
    },
    {
      slug: 'claude-code-on-the-web',
      title: 'A Practical Guide to Claude Code on the Web',
      tag: 'tutorial',
      tagLabel: 'Tutorial',
      date: '2026-05-11',
      readTime: '10 min',
      excerpt: 'How to set up a repo for Claude Code on the web, run sessions in the cloud, and ship changes through pull requests.',
      body: [
        'Claude Code on the web runs in an ephemeral cloud container. That changes how you set up a repo.',
        'The key: a SessionStart hook that installs dependencies and verifies tests run, so every session starts ready.',
        'We walk through configuring the environment, network policy, and the PR-based workflow.',
      ],
    },
  ];

  /* ─── Shop products ─────────────────────────────────────── */
  const products = [
    {
      id: 'prompt-pack-pro',
      title: 'Prompt Pack Pro',
      kind: 'Prompt Pack',
      price: 29,
      desc: '50 battle-tested prompts for coding, content, and research — organized and tagged.',
      features: ['50 prompts', 'Notion database included', 'Lifetime updates'],
      badge: 'Bestseller',
    },
    {
      id: 'skill-pack-builder',
      title: 'Claude Skill Pack',
      kind: 'Skill Pack',
      price: 49,
      desc: 'Ten ready-to-install Claude skills for common solopreneur workflows.',
      features: ['10 SKILL.md files', 'Install guide', 'Compatible with Claude Code'],
      badge: null,
    },
    {
      id: 'agent-starter-kit',
      title: 'Agent Starter Kit',
      kind: 'Starter Kit',
      price: 79,
      desc: 'Everything to ship your first multi-agent system — structure, manifests, and router.',
      features: ['Agent pack template', 'Router boilerplate', 'Video walkthrough'],
      badge: null,
    },
    {
      id: 'mcp-starter-kit',
      title: 'MCP Starter Kit',
      kind: 'Starter Kit',
      price: 59,
      desc: 'Scaffold, test, and ship your first MCP server with confidence.',
      features: ['Server boilerplate', 'Spec generator access', 'Debugging checklist'],
      badge: 'New',
    },
    {
      id: 'notion-template-bundle',
      title: 'Notion Template Bundle',
      kind: 'Templates',
      price: 19,
      desc: 'The prompt database, build tracker, and product pipeline — all in one bundle.',
      features: ['3 Notion templates', 'Setup video', 'Lifetime updates'],
      badge: null,
    },
    {
      id: 'build-audit',
      title: 'Build Audit (Done For You)',
      kind: 'Service',
      price: 199,
      desc: 'I personally audit your AI build and deliver a prioritized fix list within 5 days.',
      features: ['Full build review', 'Prioritized fix list', '30-min call'],
      badge: 'Service',
    },
  ];

  /* ─── Changelog entries ─────────────────────────────────── */
  const changelog = [
    {
      date: '2026-06-18',
      version: 'v0.4',
      type: 'added',
      title: 'Multi-page site launch',
      items: ['Full Tools, Library, Blog, Shop, and Build Studio pages', 'Working library search and filters', 'Asset detail pages'],
    },
    {
      date: '2026-06-14',
      version: 'v0.3',
      type: 'added',
      title: 'Build Log goes live',
      items: ['First case study published', 'Blog post detail pages', 'New tag system'],
    },
    {
      date: '2026-06-10',
      version: 'v0.2',
      type: 'updated',
      title: 'Library assets refreshed',
      items: ['Claude Code System Prompt updated to v2.1', 'GitHub MCP Server retested', 'Compatibility data added'],
    },
    {
      date: '2026-06-01',
      version: 'v0.1',
      type: 'added',
      title: 'AISolutionsOS prototype',
      items: ['Landing page', 'Tool previews', 'Initial library structure'],
    },
  ];

  /* ─── Glossary ──────────────────────────────────────────── */
  const glossary = [
    { term: 'MCP', full: 'Model Context Protocol', def: 'An open standard that lets AI tools connect to external systems through servers exposing tools and resources.' },
    { term: 'CLI', full: 'Command-Line Interface', def: 'A text-based program you run in a terminal by typing commands and flags.' },
    { term: 'Agent', full: 'AI Agent', def: 'An AI system that can take actions — calling tools, reading files, running steps — toward a goal, not just answering once.' },
    { term: 'Subagent', full: 'Subagent', def: 'A specialized agent spawned by a parent agent to handle a focused part of a larger task.' },
    { term: 'Hook', full: 'Hook', def: 'A script the harness runs automatically at a defined moment (e.g. session start, before a tool call).' },
    { term: 'Skill', full: 'Skill', def: 'Reusable instructions and knowledge an AI tool can load on demand to perform a specific kind of task.' },
    { term: 'Plugin', full: 'Plugin', def: 'A distributable bundle of skills, commands, and configuration that extends an AI tool.' },
    { term: 'AGENTS.md', full: 'AGENTS.md', def: 'A repo file giving coding agents project-specific instructions and conventions.' },
    { term: 'CLAUDE.md', full: 'CLAUDE.md', def: 'Claude Code’s project memory file — conventions, commands, and context loaded each session.' },
    { term: 'SaaT', full: 'Software as a Tool', def: 'A small, focused internal tool that does one job well — often the seed of a future product.' },
    { term: 'Workflow', full: 'Workflow', def: 'A defined sequence of steps to accomplish a repeatable task.' },
    { term: 'Automation', full: 'Automation', def: 'A workflow that runs without manual steps, usually triggered by an event or schedule.' },
    { term: 'Prompt Pack', full: 'Prompt Pack', def: 'A curated, organized collection of prompts sold or shared as a unit.' },
    { term: 'Context File', full: 'Context File', def: 'A file (like CLAUDE.md) that supplies persistent background an AI tool reads automatically.' },
    { term: 'Tool Call', full: 'Tool Call', def: 'When an AI model invokes an external function or tool to get information or take an action.' },
    { term: 'RAG', full: 'Retrieval-Augmented Generation', def: 'A technique where relevant documents are retrieved and fed to the model to ground its answers.' },
  ];

  /* ─── Learning paths ────────────────────────────────────── */
  const paths = [
    { id: 'beginner', title: 'Beginner AI Builder Path', steps: 5, desc: 'Start from zero. Learn prompts, tools, and your first reusable asset.', color: 'blue' },
    { id: 'prompt-to-product', title: 'Prompt-to-Product Path', steps: 6, desc: 'Turn a prompt you already use into a packaged, sellable product.', color: 'purple' },
    { id: 'skill-builder', title: 'Claude Skill Builder Path', steps: 4, desc: 'Go from a manual workflow to a clean, installable Claude skill.', color: 'cyan' },
    { id: 'mcp-builder', title: 'MCP Server Builder Path', steps: 5, desc: 'Spec, scaffold, test, and ship your first MCP server.', color: 'blue' },
    { id: 'monetization', title: 'AI Creator Monetization Path', steps: 7, desc: 'Build a small catalog of paid assets and a simple shop.', color: 'purple' },
    { id: 'automation', title: 'Solopreneur Automation Path', steps: 6, desc: 'Automate the repetitive parts of running a one-person business.', color: 'cyan' },
  ];

  /* ─── Compatibility matrix ──────────────────────────────── */
  const compatTools = ['Claude', 'ChatGPT', 'Gemini', 'Codex', 'Cursor', 'GitHub', 'Vercel', 'Notion', 'n8n', 'Zapier', 'Supabase', 'Airtable'];

  /* ─── Site-wide nav definition (single source of truth) ──── */
  const nav = [
    { label: 'Home', href: 'index.html' },
    { label: 'Tools', href: 'tools.html' },
    { label: 'AI Library', href: 'library.html' },
    { label: 'Blog', href: 'blog.html' },
    { label: 'Build Studio', href: 'build-studio.html' },
    { label: 'Shop', href: 'shop.html' },
    { label: 'Changelog', href: 'changelog.html' },
  ];

  window.AISO = {
    tools: tools,
    library: library,
    posts: posts,
    products: products,
    changelog: changelog,
    glossary: glossary,
    paths: paths,
    compatTools: compatTools,
    nav: nav,

    /* Lookup helpers */
    getTool: function (id) { return tools.find(function (t) { return t.id === id; }); },
    getAsset: function (id) { return library.find(function (a) { return a.id === id; }); },
    getPost: function (slug) { return posts.find(function (p) { return p.slug === slug; }); },
    getProduct: function (id) { return products.find(function (p) { return p.id === id; }); },
  };
})();
