/**
 * AISolutionsOS — data.js
 * Single source of truth for all site content.
 * Exposed globally as window.AISO so every page can render from it.
 */
(function () {
  'use strict';

  /* ─── Tools (Build Studio) ──────────────────────────────── */
  const tools = [
    {
      id: 'prompt-to-product',
      title: 'Prompt-to-Product Packager',
      tagline: 'Package any prompt into a sellable product',
      desc: 'Package any prompt into a sellable product with structured metadata, pricing, and delivery copy.',
      icon: 'doc',
      status: 'live',
      category: 'Productize',
      tags: ['monetization', 'product building', 'content'],
    },
    {
      id: 'workflow-to-skill',
      title: 'Workflow-to-Skill Builder',
      tagline: 'Convert workflows into Claude skills',
      desc: 'Convert your workflows into reusable Claude skills with proper SKILL.md formatting and frontmatter.',
      icon: 'layers',
      status: 'live',
      category: 'Build',
      tags: ['coding', 'automation'],
    },
    {
      id: 'mcp-spec-generator',
      title: 'MCP Spec Generator',
      tagline: 'Generate MCP server specs instantly',
      desc: 'Generate a complete MCP server spec — tools, resources, and schema — from a plain-language description.',
      icon: 'nodes',
      status: 'live',
      category: 'Build',
      tags: ['coding', 'automation'],
    },
    {
      id: 'cli-scaffold-studio',
      title: 'CLI Scaffold Studio',
      tagline: 'Scaffold CLI tools from descriptions',
      desc: 'Scaffold production-ready CLI tools from natural language descriptions with command trees and flags.',
      icon: 'terminal',
      status: 'soon',
      category: 'Build',
      tags: ['coding'],
    },
    {
      id: 'automation-planner',
      title: 'Automation Planner',
      tagline: 'Plan n8n/Zapier automations visually',
      desc: 'Plan and visualize n8n/Zapier automations with AI-generated logic flows and trigger maps.',
      icon: 'flow',
      status: 'soon',
      category: 'Plan',
      tags: ['automation', 'monetization'],
    },
    {
      id: 'build-audit-checker',
      title: 'Build Audit Checker',
      tagline: 'Audit your AI builds for gaps',
      desc: 'Audit your AI builds for gaps, missing components, and improvement areas with a scored checklist.',
      icon: 'check',
      status: 'live',
      category: 'Audit',
      tags: ['product building', 'research'],
    },
    {
      id: 'agent-pack-generator',
      title: 'Agent Pack Generator',
      tagline: 'Bundle agents into deployable packs',
      desc: 'Bundle multiple agents into structured, deployable agent packs with manifests and routing.',
      icon: 'shield',
      status: 'soon',
      category: 'Build',
      tags: ['coding', 'automation'],
    },
    {
      id: 'content-repurposing',
      title: 'Content Repurposing Console',
      tagline: 'Turn one piece into many assets',
      desc: 'Turn one piece of content into multiple formats and distribution assets across platforms.',
      icon: 'grid',
      status: 'soon',
      category: 'Content',
      tags: ['content', 'monetization'],
    },
    {
      id: 'saat-builder',
      title: 'SaaT Builder',
      tagline: 'Turn a workflow into a small internal tool',
      desc: 'Turn an internal workflow into a small Software-as-a-Tool dashboard spec — screens, data model, and actions.',
      icon: 'layers',
      status: 'soon',
      category: 'Build',
      tags: ['product building', 'automation'],
    },
    {
      id: 'ai-tool-demo-builder',
      title: 'AI Tool Demo Builder',
      tagline: 'Generate an interactive demo for any AI tool',
      desc: 'Generate an interactive demo or walkthrough for any AI tool you built, ready to embed on a product page.',
      icon: 'grid',
      status: 'soon',
      category: 'Content',
      tags: ['content', 'product building'],
    },
    {
      id: 'signal-to-asset-dashboard',
      title: 'Signal-to-Asset Research Dashboard',
      tagline: 'Track AI news, convert it into buildable ideas',
      desc: 'Track AI news signals and convert the useful ones into buildable asset ideas with a scored backlog.',
      icon: 'flow',
      status: 'soon',
      category: 'Plan',
      tags: ['research', 'product building'],
    },
    {
      id: 'ai-tool-directory',
      title: 'AI Tool Directory & Update Tracker',
      tagline: 'A tracked directory of AI tools that flags staleness',
      desc: 'A tracked directory of AI tools with freshness and staleness alerts so your recommendations do not go stale.',
      icon: 'check',
      status: 'soon',
      category: 'Audit',
      tags: ['research', 'automation'],
    },
  ];

  /* ─── Library assets ────────────────────────────────────── */
  const library = [
    {
      id: 'claude-code-system-prompt',
      title: 'Claude Code System Prompt',
      type: 'prompt',
      typeLabel: 'Prompt',
      desc: 'A battle-tested system prompt for running Claude Code on complex multi-file projects.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '2.1.0',
      updated: '2026-06-10',
      forWho: 'Developers running Claude Code on large codebases.',
      problem: 'Default prompting drifts on big repos — losing track of architecture and conventions.',
      inputs: 'Your repo structure and a short description of conventions.',
      output: 'A drop-in system prompt that keeps Claude anchored to your codebase.',
      setup: 'Copy the prompt into your CLAUDE.md or system prompt field. Adjust the conventions block.',
      example: 'You are working in a TypeScript monorepo. Always match the surrounding code style...',
      content: 'You are an expert software engineer working in this repository. Before editing, read the surrounding code and match its conventions exactly. Prefer minimal diffs. Never invent APIs — verify against the codebase first.',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '2 min',
      rating: 5,
      limitations: 'Tuned for TypeScript/JS-heavy repos; needs adjustment for other stacks.',
      monetization: 'Use it as-is in client Claude Code setups to speed up onboarding on new codebases.',
    },
    {
      id: 'github-mcp-server',
      title: 'GitHub MCP Server',
      type: 'mcp',
      typeLabel: 'MCP Server',
      desc: 'Full GitHub integration via MCP — repos, PRs, issues, and file operations.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '1.4.2',
      updated: '2026-06-08',
      forWho: 'Anyone automating GitHub workflows from an AI agent.',
      problem: 'Manually copy-pasting between GitHub and your AI tool is slow and error-prone.',
      inputs: 'A GitHub personal access token with repo scope.',
      output: 'A running MCP server exposing repo, PR, and issue tools.',
      setup: 'Add the server to your MCP config, set GITHUB_TOKEN, and restart your client.',
      example: 'list_pull_requests(owner="acme", repo="web") → returns open PRs.',
      content: '{\n  "mcpServers": {\n    "github": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-github"],\n      "env": { "GITHUB_TOKEN": "<your-token>" }\n    }\n  }\n}',
      license: 'commercial',
      requires: 'GitHub personal access token',
      risk: 'medium',
      setupDifficulty: 'moderate',
      timeToUse: '10 min',
      rating: 4,
      limitations: 'Token scope must be managed carefully — broad repo access if over-scoped.',
      monetization: 'Offer as part of a client automation setup that needs GitHub read/write from an agent.',
    },
    {
      id: 'workflow-to-skill-converter',
      title: 'Workflow-to-Skill Converter',
      type: 'skill',
      typeLabel: 'Skill',
      desc: 'Convert any documented workflow into a properly structured Claude skill file.',
      status: 'draft',
      free: true,
      difficulty: 'beginner',
      useCase: 'automation',
      compat: ['claude'],
      version: '0.3.0',
      updated: '2026-06-15',
      forWho: 'Builders who keep repeating the same multi-step process.',
      problem: 'Workflows live in your head or scattered docs — not reusable by an agent.',
      inputs: 'A written description of your workflow steps.',
      output: 'A SKILL.md file with frontmatter, triggers, and instructions.',
      setup: 'Drop the generated SKILL.md into .claude/skills/<name>/.',
      example: '---\nname: weekly-report\ndescription: Generate the weekly metrics report\n---',
      content: '---\nname: your-skill\ndescription: When to use this skill\n---\n\n# Steps\n1. ...\n2. ...',
      license: 'personal',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '15 min',
      rating: 3,
      limitations: 'Still in draft — output frontmatter sometimes needs manual cleanup.',
      monetization: 'Use internally to turn your own SOPs into sellable skill files faster.',
    },
    {
      id: 'ai-build-audit-checklist',
      title: 'AI Build Audit Checklist',
      type: 'checklist',
      typeLabel: 'Checklist',
      desc: 'A comprehensive checklist to audit any AI build for gaps and missing pieces.',
      status: 'tested',
      free: true,
      difficulty: 'beginner',
      useCase: 'product building',
      compat: ['claude', 'gpt'],
      version: '1.0.0',
      updated: '2026-06-01',
      forWho: 'Solopreneurs shipping AI products who want a quality bar.',
      problem: 'It is easy to ship an AI build with silent gaps — no error handling, no docs, no tests.',
      inputs: 'Your project, open in front of you.',
      output: 'A scored audit highlighting what is missing.',
      setup: 'Run through each item and mark pass/fail. Use the Build Audit Checker tool to score it.',
      example: '☐ Inputs validated  ☐ Errors handled  ☐ Docs written  ☐ Tested',
      content: '1. Inputs validated\n2. Errors handled gracefully\n3. Output format documented\n4. Compatibility stated\n5. Tested end-to-end\n6. Pricing / use-case noted',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '10 min',
      rating: 4,
      limitations: 'Checklist is generic — pair with domain-specific checks for regulated industries.',
      monetization: 'Run it as a paid audit deliverable for clients shipping AI features.',
    },
    {
      id: 'prompt-to-product-sop',
      title: 'Prompt-to-Product SOP',
      type: 'template',
      typeLabel: 'Template',
      desc: 'Step-by-step SOP for packaging a raw prompt into a productized, sellable asset.',
      status: 'tested',
      free: false,
      difficulty: 'intermediate',
      useCase: 'monetization',
      compat: ['claude', 'gpt', 'gemini'],
      version: '2.0.0',
      updated: '2026-05-28',
      forWho: 'Creators who want to sell prompts as real products.',
      problem: 'A raw prompt is not a product — it needs packaging, pricing, and delivery.',
      inputs: 'One prompt you already use and trust.',
      output: 'A complete product page outline with pricing tiers.',
      setup: 'Follow the 7 steps in order. Pair with the Prompt-to-Product Packager tool.',
      example: 'Step 1: Name the outcome. Step 2: Define the buyer...',
      content: 'Step 1 — Name the outcome\nStep 2 — Define the buyer\nStep 3 — Write the promise\nStep 4 — Package the prompt\nStep 5 — Price it\nStep 6 — Write delivery copy\nStep 7 — Ship',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'moderate',
      timeToUse: '30 min',
      rating: 5,
      limitations: 'Assumes you already have a working prompt — does not help you find one.',
      monetization: 'Use the SOP itself as a paid mini-course or resell it packaged.',
    },
    {
      id: 'agent-pack-starter-kit',
      title: 'Agent Pack Starter Kit',
      type: 'template',
      typeLabel: 'Template',
      desc: 'A starter template for bundling multiple AI agents into a deployable agent pack.',
      status: 'draft',
      free: true,
      difficulty: 'advanced',
      useCase: 'coding',
      compat: ['claude'],
      version: '0.2.1',
      updated: '2026-06-16',
      forWho: 'Advanced builders shipping multi-agent systems.',
      problem: 'Multi-agent setups get messy without a clear pack structure.',
      inputs: 'A list of agents and their responsibilities.',
      output: 'A folder structure and manifest for a deployable agent pack.',
      setup: 'Clone the structure, fill in each agent definition, wire the router.',
      example: 'agents/\n  researcher.md\n  writer.md\n  editor.md\nmanifest.json',
      content: '{\n  "name": "content-pack",\n  "agents": ["researcher", "writer", "editor"],\n  "router": "orchestrator"\n}',
      license: 'personal',
      requires: 'None',
      risk: 'medium',
      setupDifficulty: 'involved',
      timeToUse: '45 min',
      rating: 3,
      limitations: 'Draft status — router wiring needs manual work for non-trivial agent counts.',
      monetization: 'Base a client multi-agent build on this structure to save setup time.',
    },
    {
      id: 'notion-prompt-database',
      title: 'Notion Prompt Database',
      type: 'template',
      typeLabel: 'Template',
      desc: 'A ready-made Notion database for cataloging, tagging, and reusing your prompts.',
      status: 'tested',
      free: false,
      difficulty: 'beginner',
      useCase: 'content',
      compat: ['claude', 'gpt', 'gemini'],
      version: '1.2.0',
      updated: '2026-05-20',
      forWho: 'Anyone drowning in scattered prompts across tabs and notes.',
      problem: 'Good prompts get lost. There is no system to find or reuse them.',
      inputs: 'A free Notion account.',
      output: 'A structured database with tags, status, and compatibility fields.',
      setup: 'Duplicate the template into your workspace and start adding prompts.',
      example: 'Fields: Title, Type, Tool, Status, Use case, Rating',
      content: 'Duplicate the Notion template, then map your prompts into the fields.',
      license: 'commercial',
      requires: 'Notion account',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '5 min',
      rating: 4,
      limitations: 'Notion-only — no export path if you switch tools later.',
      monetization: 'Sell it as a template bundle or use it to onboard clients into your prompt system.',
    },
    {
      id: 'repo-cleanup-cli',
      title: 'Repo Cleanup CLI',
      type: 'cli',
      typeLabel: 'CLI',
      desc: 'A small CLI that audits a repo for stale branches, large files, and missing docs.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '0.9.0',
      updated: '2026-06-12',
      forWho: 'Developers who want a quick repo health check.',
      problem: 'Repos accumulate cruft — stale branches, oversized files, missing READMEs.',
      inputs: 'A local git repository.',
      output: 'A printed report of issues found.',
      setup: 'npm i -g repo-cleanup, then run `repo-cleanup .` in your repo.',
      example: '$ repo-cleanup .  →  3 stale branches, 1 file > 5MB, no LICENSE',
      content: '#!/usr/bin/env node\n// scans cwd git repo and prints a health report',
      license: 'commercial',
      requires: 'Node.js and git installed locally',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '5 min',
      rating: 4,
      limitations: 'Read-only audit — does not auto-fix issues it finds.',
      monetization: 'Run it as part of a paid repo health-check service.',
    },
    {
      id: 'daily-digest-automation',
      title: 'Daily Digest Automation',
      type: 'automation',
      typeLabel: 'Automation',
      desc: 'An n8n flow that pulls your sources each morning and sends an AI-summarized digest.',
      status: 'tested',
      free: false,
      difficulty: 'intermediate',
      useCase: 'automation',
      compat: ['claude', 'gpt'],
      version: '1.1.0',
      updated: '2026-06-05',
      forWho: 'Anyone who wants a curated morning briefing, hands-off.',
      problem: 'Manually checking 10 sources every morning wastes the best hour of your day.',
      inputs: 'n8n instance, your source URLs/feeds, an LLM API key.',
      output: 'A daily summarized email or Slack message.',
      setup: 'Import the workflow JSON into n8n, set credentials, schedule it.',
      example: 'Trigger: 7am daily → Fetch sources → Summarize → Email',
      content: '{ "nodes": [ { "type": "schedule" }, { "type": "http" }, { "type": "llm" }, { "type": "email" } ] }',
      license: 'commercial',
      requires: 'n8n instance and an LLM API key',
      risk: 'medium',
      setupDifficulty: 'moderate',
      timeToUse: '20 min',
      rating: 4,
      limitations: 'Summary quality depends on source feed quality — garbage in, garbage out.',
      monetization: 'White-label it as a "daily briefing" service for clients or a niche newsletter.',
    },
    {
      id: 'solopreneur-prompt-pack',
      title: 'Solopreneur Prompt Pack',
      type: 'prompt-pack',
      typeLabel: 'Prompt Pack',
      desc: '12 prompts covering the daily and weekly tasks of running a one-person AI business.',
      status: 'published',
      free: true,
      difficulty: 'beginner',
      useCase: 'automation',
      compat: ['claude', 'gpt', 'gemini'],
      version: '1.0.0',
      updated: '2026-07-10',
      forWho: 'Solopreneurs running an AI-based business without a team.',
      problem: 'You reinvent the same prompts for planning, content, and admin every week.',
      inputs: 'None — prompts are ready to copy and adapt with your own details.',
      output: '12 categorized prompts covering planning, content, outreach, and admin.',
      setup: 'Copy the prompts into your tool of choice and fill in the bracketed placeholders.',
      example: '"Turn this week\'s wins and blockers into a 3-line investor-style update: [notes]"',
      content: '1. Weekly plan generator\n2. Daily priority triage\n3. Content idea batch (10 ideas from 1 topic)\n4. Cold outreach opener\n5. Client update summary\n6. Pricing objection response\n7. Invoice follow-up\n8. Weekly metrics recap\n9. Competitor scan prompt\n10. Burnout check-in prompt\n11. Offer tightening prompt\n12. End-of-week retro prompt',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '5 min',
      rating: 4,
      limitations: 'Generic by design — swap in your own voice and specifics before using client-facing.',
      monetization: 'Repackage as a lead magnet or bundle into a paid solopreneur starter kit.',
    },
    {
      id: 'meeting-notes-workflow',
      title: 'Meeting Notes → Status Update Workflow',
      type: 'workflow',
      typeLabel: 'Workflow',
      desc: 'A repeatable workflow that turns raw meeting notes into a client-ready status update.',
      status: 'tested',
      free: true,
      difficulty: 'beginner',
      useCase: 'automation',
      compat: ['claude', 'gpt', 'notion'],
      version: '1.1.0',
      updated: '2026-07-05',
      forWho: 'Freelancers and consultants who run client meetings.',
      problem: 'Notes pile up in a doc and never turn into a status update anyone reads.',
      inputs: 'Raw meeting notes or a transcript.',
      output: 'A formatted status update with decisions, action items, and owners.',
      setup: 'Paste notes into the prompt, run it, then drop the output into Notion or email.',
      example: 'Input: bullet notes → Output: "Decisions: ... Action items: ... Next meeting: ..."',
      content: 'Step 1 — Paste raw notes\nStep 2 — Run extraction prompt (decisions / action items / owners / dates)\nStep 3 — Format into status update template\nStep 4 — Send or log in Notion',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '5 min',
      rating: 4,
      limitations: 'Struggles with very long or multi-topic transcripts without pre-splitting.',
      monetization: 'Offer as a value-add for retainer clients — send status updates without extra meeting time.',
    },
    {
      id: 'yt-transcript-script',
      title: 'YouTube Transcript Summarizer Script',
      type: 'script',
      typeLabel: 'Script',
      desc: 'A Python script that pulls a YouTube video transcript and generates a structured summary.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'research',
      compat: ['gpt', 'claude'],
      version: '1.0.2',
      updated: '2026-07-01',
      forWho: 'Researchers and content creators who process a lot of video.',
      problem: 'Watching full videos for a few useful points is a poor use of time.',
      inputs: 'A YouTube video URL and an LLM API key.',
      output: 'A structured summary with key points, quotes, and timestamps.',
      setup: 'pip install the requirements, set your API key as an env var, run `python summarize.py <url>`.',
      example: '$ python summarize.py https://youtu.be/xyz → prints summary.md',
      content: 'import sys\n# 1. fetch transcript via youtube-transcript-api\n# 2. chunk transcript\n# 3. summarize each chunk, then summarize the summaries\n# 4. write summary.md with key points and timestamps',
      license: 'personal',
      requires: 'YouTube video with captions, LLM API key',
      risk: 'low',
      setupDifficulty: 'moderate',
      timeToUse: '10 min',
      rating: 4,
      limitations: 'Only works on videos with available captions/transcripts.',
      monetization: 'Wrap it in a small paid tool for creators who need fast video research digests.',
    },
    {
      id: 'codex-agents-md',
      title: 'Codex AGENTS.md Starter',
      type: 'agents-md',
      typeLabel: 'AGENTS.md',
      desc: 'A starter AGENTS.md file for Codex with project conventions, guardrails, and do-not-touch rules.',
      status: 'draft',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['codex'],
      version: '0.4.0',
      updated: '2026-07-08',
      forWho: 'Teams running OpenAI Codex on a real codebase.',
      problem: 'Codex without project context makes reasonable-looking changes that violate your conventions.',
      inputs: 'Your repo\'s conventions, test commands, and any protected files.',
      output: 'An AGENTS.md file Codex reads automatically at session start.',
      setup: 'Copy AGENTS.md into your repo root, fill in the bracketed sections, commit it.',
      example: '## Guardrails\n- Never edit /migrations directly\n- Run `npm test` before proposing a PR',
      content: '# AGENTS.md\n\n## Conventions\n- [language/style rules]\n\n## Commands\n- Test: [command]\n- Lint: [command]\n\n## Guardrails\n- Do not edit: [protected paths]\n- Always: [required steps before finishing]',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '15 min',
      rating: 3,
      limitations: 'Still draft — guardrail section needs to be tailored per repo, not copy-pasted blindly.',
      monetization: 'Use it as the starting point when onboarding Codex on client codebases.',
    },
    {
      id: 'gemini-md-workflow',
      title: 'GEMINI.md Context File',
      type: 'gemini-md',
      typeLabel: 'GEMINI.md',
      desc: 'A GEMINI.md context file that gives Gemini CLI persistent project context, mirroring CLAUDE.md.',
      status: 'draft',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['gemini'],
      version: '0.3.0',
      updated: '2026-07-09',
      forWho: 'Developers using Gemini CLI on multi-file projects.',
      problem: 'Gemini CLI starts fresh every session with no memory of your project structure or rules.',
      inputs: 'Your project structure, conventions, and key commands.',
      output: 'A GEMINI.md file Gemini CLI loads automatically as project context.',
      setup: 'Place GEMINI.md at your project root, fill in sections, restart the CLI session.',
      example: '## Project\nA Next.js app. Use App Router. Never edit /generated.',
      content: '# GEMINI.md\n\n## Project overview\n[one paragraph]\n\n## Conventions\n- [style / structure rules]\n\n## Commands\n- Build: [command]\n- Test: [command]\n\n## Do not\n- [protected paths / actions]',
      license: 'commercial',
      requires: 'Gemini CLI installed',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '15 min',
      rating: 3,
      limitations: 'Draft — Gemini CLI context conventions are still evolving, revisit each update.',
      monetization: 'Bundle with the Codex AGENTS.md starter as a "context files for every agent" pack.',
    },
    {
      id: 'research-subagent',
      title: 'Research Subagent Definition',
      type: 'subagent',
      typeLabel: 'Subagent',
      desc: 'A research subagent definition with a defined toolset, scope limits, and a strict output contract.',
      status: 'tested',
      free: false,
      difficulty: 'advanced',
      useCase: 'research',
      compat: ['claude'],
      version: '1.0.1',
      updated: '2026-07-03',
      forWho: 'Builders orchestrating multi-agent systems that need reliable research output.',
      problem: 'A general-purpose agent asked to "research this" returns inconsistent, hard-to-parse output.',
      inputs: 'A research question and any source constraints.',
      output: 'A subagent definition that returns findings in a fixed, parseable structure.',
      setup: 'Drop the definition into your subagent config, wire it into your orchestrator.',
      example: 'Output contract: { claim, evidence[], confidence, sources[] }',
      content: '---\nname: research-subagent\ndescription: Use for focused research questions requiring cited findings\ntools: WebSearch, WebFetch, Read\n---\n\nReturn findings as: { claim, evidence[], confidence: low|medium|high, sources[] }. Never state a claim without at least one source.',
      license: 'commercial',
      requires: 'Claude with subagent support, web search tool access',
      risk: 'medium',
      setupDifficulty: 'moderate',
      timeToUse: '15 min',
      rating: 4,
      limitations: 'Output quality depends heavily on the parent orchestrator enforcing the contract.',
      monetization: 'License it as the research layer inside a client-facing research product.',
    },
    {
      id: 'pre-commit-hook',
      title: 'Lint + Test Pre-Commit Hook',
      type: 'hook',
      typeLabel: 'Hook',
      desc: 'A Claude Code hook that runs lint and tests before allowing a commit to proceed.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude'],
      version: '1.0.0',
      updated: '2026-07-02',
      forWho: 'Developers who want Claude Code to self-check before committing.',
      problem: 'Agents commit code with failing tests or lint errors when nothing stops them.',
      inputs: 'Your project\'s lint and test commands.',
      output: 'A hook that blocks the commit tool call until checks pass.',
      setup: 'Add the hook to .claude/settings.json under PreToolUse for the git commit command.',
      example: '$ git commit → hook runs `npm run lint && npm test` → blocks on failure',
      content: '{\n  "hooks": {\n    "PreToolUse": [\n      {\n        "matcher": "Bash(git commit*)",\n        "hooks": [{ "type": "command", "command": "npm run lint && npm test" }]\n      }\n    ]\n  }\n}',
      license: 'commercial',
      requires: 'Claude Code, a configured lint/test command',
      risk: 'low',
      setupDifficulty: 'moderate',
      timeToUse: '10 min',
      rating: 4,
      limitations: 'Slows down commits on large test suites — consider scoping to changed files.',
      monetization: 'Include it as a standard part of any client Claude Code environment setup you sell.',
    },
    {
      id: 'content-engine-plugin',
      title: 'Content Engine Plugin',
      type: 'plugin',
      typeLabel: 'Plugin',
      desc: 'A Claude plugin bundling three skills — ideation, drafting, and repurposing — into one content engine.',
      status: 'published',
      free: false,
      difficulty: 'intermediate',
      useCase: 'content',
      compat: ['claude'],
      version: '1.2.0',
      updated: '2026-07-11',
      forWho: 'Creators and marketers who publish across multiple formats regularly.',
      problem: 'Idea, draft, and repurpose steps live in separate disconnected prompts.',
      inputs: 'A topic or raw source material.',
      output: 'A draft plus repurposed variants (thread, short-form, newsletter blurb).',
      setup: 'Install the plugin via your plugin marketplace config, then invoke its skills by name.',
      example: '/content-idea "AI agents" → 10 angles → /content-draft best angle → /content-repurpose draft',
      content: '{\n  "name": "content-engine",\n  "skills": ["content-idea", "content-draft", "content-repurpose"],\n  "version": "1.2.0"\n}',
      license: 'commercial',
      requires: 'Claude with plugin support',
      risk: 'low',
      setupDifficulty: 'moderate',
      timeToUse: '15 min',
      rating: 5,
      limitations: 'Repurposing skill is tuned for text-first platforms, not video scripts.',
      monetization: 'Sell seats or a license to creators as a monthly content-ops tool.',
    },
    {
      id: 'client-onboarding-sop',
      title: 'Client Onboarding SOP',
      type: 'sop',
      typeLabel: 'SOP',
      desc: 'A client onboarding SOP for AI service providers — from signed contract to first delivery.',
      status: 'published',
      free: false,
      difficulty: 'beginner',
      useCase: 'monetization',
      compat: ['notion'],
      version: '1.0.0',
      updated: '2026-06-28',
      forWho: 'Freelancers and agencies delivering AI builds for clients.',
      problem: 'Every new client gets a slightly different, ad-hoc onboarding — some steps get missed.',
      inputs: 'Your service offering and standard deliverables.',
      output: 'A step-by-step onboarding SOP with checklist and email templates.',
      setup: 'Duplicate the SOP into your workspace, adapt the steps and templates to your service.',
      example: 'Step 1: Send welcome + intake form. Step 2: Kickoff call. Step 3: Access + credentials checklist...',
      content: '1. Send welcome email + intake form\n2. Schedule kickoff call\n3. Collect access/credentials (checklist)\n4. Confirm scope and timeline in writing\n5. Set up shared workspace\n6. Deliver first milestone\n7. Collect feedback + testimonial ask',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '20 min',
      rating: 4,
      limitations: 'Written for solo/small-team delivery — adapt for larger agency handoffs.',
      monetization: 'Use it directly to professionalize client delivery, or resell as an agency-ops template.',
    },
    {
      id: 'solopreneur-tool-stack',
      title: 'The Solopreneur AI Tool Stack',
      type: 'tool-stack',
      typeLabel: 'Tool Stack',
      desc: 'The exact tool stack — with reasoning for each pick — for running an AI solopreneur business.',
      status: 'published',
      free: true,
      difficulty: 'beginner',
      useCase: 'product building',
      compat: ['claude', 'notion', 'vercel', 'supabase'],
      version: '1.0.0',
      updated: '2026-06-30',
      forWho: 'Anyone deciding what to actually pay for as a solo AI builder.',
      problem: 'There are hundreds of tool options and no honest "here is what I actually use and why."',
      inputs: 'None.',
      output: 'A categorized list of tools with the reason each earned a spot in the stack.',
      setup: 'Read through and swap in your own picks where you have a strong preference.',
      example: 'Coding: Claude Code (agentic, fits CLAUDE.md workflow). Hosting: Vercel (zero-config, fast previews).',
      content: 'Coding: Claude Code\nHosting/deploy: Vercel\nDatabase/auth: Supabase\nDocs/CRM-lite: Notion\nAutomation: n8n\nPayments: Stripe\nEach pick includes a one-line "why" in the full write-up.',
      license: 'personal',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '10 min',
      rating: 4,
      limitations: 'Reflects one builder\'s stack and biases — not an exhaustive market comparison.',
      monetization: 'Use as a lead magnet that funnels into paid stack-specific templates.',
    },
    {
      id: 'mcp-official-docs',
      title: 'MCP Official Docs — Reading Order',
      type: 'docs',
      typeLabel: 'Official Docs',
      desc: 'A curated, ordered link-map of the official MCP documentation actually worth reading.',
      status: 'published',
      free: true,
      difficulty: 'beginner',
      useCase: 'research',
      compat: ['claude'],
      version: '1.0.0',
      updated: '2026-06-25',
      forWho: 'Anyone learning MCP from scratch who does not want to read everything.',
      problem: 'The official MCP docs are complete but not ordered for a first-time learner.',
      inputs: 'None.',
      output: 'An ordered reading list with a one-line note on why each page matters.',
      setup: 'Read top to bottom, skip sections not relevant to your use case (noted inline).',
      example: '1. Concepts overview (read first) 2. Server quickstart (skip if using an existing server)...',
      content: '1. MCP concepts overview — start here, 10 min\n2. Server quickstart — build your first server\n3. Tools spec — how tool schemas work\n4. Resources spec — optional, skip if not exposing files\n5. Client quickstart — connecting a client\n6. Transport spec — advanced, only if debugging connections',
      license: 'personal',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '30 min',
      rating: 4,
      limitations: 'Links point to docs that move — some URLs may need re-verifying over time.',
      monetization: 'Not directly monetizable — use it to shorten your own MCP onboarding time.',
    },
    {
      id: 'agent-repo-collection',
      title: 'Annotated Agent Repo Collection',
      type: 'repo',
      typeLabel: 'GitHub Repo',
      desc: 'An annotated collection of example agent repos worth studying, with notes on what each teaches.',
      status: 'tested',
      free: true,
      difficulty: 'intermediate',
      useCase: 'coding',
      compat: ['claude', 'github', 'codex'],
      version: '1.1.0',
      updated: '2026-07-04',
      forWho: 'Builders who learn best from reading real code, not docs.',
      problem: 'Most "awesome agent" lists are unannotated link dumps with no guidance on what to actually study.',
      inputs: 'None.',
      output: 'A short list of repos, each with what pattern to look for and where.',
      setup: 'Clone each repo, open the annotated file/folder noted for that entry first.',
      example: 'repo-x/orchestrator.ts — study the retry + backoff pattern around line 40.',
      content: '1. [repo A] — study: multi-agent router pattern\n2. [repo B] — study: tool schema validation\n3. [repo C] — study: long-running task checkpointing\n4. [repo D] — study: hook-based guardrails',
      license: 'personal',
      requires: 'GitHub account',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '30 min',
      rating: 3,
      limitations: 'Linked repos evolve independently — patterns noted may drift from current code.',
      monetization: 'Use it to accelerate your own agent build — not intended for resale as-is.',
    },
    {
      id: 'claude-code-tutorial',
      title: 'Your First Claude Code Skill in 30 Minutes',
      type: 'tutorial',
      typeLabel: 'Tutorial',
      desc: 'A hands-on tutorial that gets you from zero to your first working Claude Code skill in 30 minutes.',
      status: 'published',
      free: true,
      difficulty: 'beginner',
      useCase: 'coding',
      compat: ['claude'],
      version: '1.0.0',
      updated: '2026-07-06',
      forWho: 'First-time Claude Code users who learn by doing.',
      problem: 'Docs explain the skill format but not the experience of building one end-to-end.',
      inputs: 'Claude Code installed and one real repeatable task you do manually.',
      output: 'A working, installed SKILL.md you use immediately after finishing.',
      setup: 'Follow the 6 steps in order — each one produces something you check off before moving on.',
      example: 'Step 3: Write the description field so Claude knows *when* to trigger the skill, not just what it does.',
      content: '1. Pick one task you repeat weekly\n2. Write the trigger description first\n3. Write the steps in plain language\n4. Save as .claude/skills/<name>/SKILL.md\n5. Trigger it manually to test\n6. Refine the description until it triggers on the right phrasing',
      license: 'commercial',
      requires: 'Claude Code installed',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '30 min',
      rating: 5,
      limitations: 'Covers a single-file skill only — multi-file skills need the reference docs.',
      monetization: 'Use it as free onboarding content that funnels readers into paid skill packs.',
    },
    {
      id: 'landing-copy-swipe-file',
      title: 'AI Product Landing Copy Swipe File',
      type: 'swipe-file',
      typeLabel: 'Swipe File',
      desc: 'A swipe file of proven landing page copy patterns specifically for AI products and tools.',
      status: 'idea',
      free: false,
      difficulty: 'beginner',
      useCase: 'monetization',
      compat: ['vercel', 'notion'],
      version: '0.1.0',
      updated: '2026-07-12',
      forWho: 'AI builders writing their own product landing pages without a copywriter.',
      problem: 'Generic copywriting advice does not address AI-specific objections (trust, hallucination, "is this just a wrapper").',
      inputs: 'None.',
      output: 'A set of headline, objection-handling, and CTA patterns annotated with when to use each.',
      setup: 'Not yet built — collecting and annotating patterns from live AI product pages.',
      example: 'Objection pattern: "Not another wrapper" → lead with the specific workflow it replaces, not the model.',
      content: 'Status: idea stage. Planned sections: hero patterns, objection-handling blocks, pricing framing, proof/trust patterns, CTA variants — each annotated with a real (anonymized) example.',
      license: 'commercial',
      requires: 'None',
      risk: 'low',
      setupDifficulty: 'easy',
      timeToUse: '15 min',
      rating: 3,
      limitations: 'Still in idea stage — not yet populated with the full pattern set.',
      monetization: 'Planned as a paid swipe file once populated; useful now only as a structure to fill in yourself.',
    },
  ];

  /* ─── Blog posts ────────────────────────────────────────── */
  const posts = [
    {
      slug: 'claude-fable-5-mythos-class-ai',
      title: 'Claude Fable 5 Is Here: What Mythos-Class AI Actually Means for Builders',
      tag: 'news',
      tagLabel: 'News',
      date: '2026-06-20',
      readTime: '9 min',
      excerpt: 'Anthropic launched Claude Fable 5 on June 9 — a new capability tier designed for tasks that take days, not minutes. Here is what actually changed and why it matters to anyone building on top of Claude.',
      body: [
        'On June 9, 2026, Anthropic launched Claude Fable 5 and introduced a new capability tier they are calling "Mythos-class." The phrase sounds like marketing, but the underlying claim is specific: Fable 5 is built for continuous, multi-day work that previous Claude models could not sustain without losing coherence or context. Whether the claim holds depends on what you are building, but the benchmarks and early reports from power users suggest this is a meaningful step change rather than an incremental release.',
        'The headline technical change is a one-million-token context window. That is not the largest context window in the market, but context alone has never been the limiting factor for most builders — quality of attention across that context has. Anthropic says Fable 5 maintains reliable retrieval and reasoning accuracy further into the context than Sonnet or Opus could, which matters for use cases like legal document analysis, large codebase refactors, and long-running research agents that accumulate a lot of history before taking action.',
        'Long-horizon agent capability is the other major focus. Anthropic shipped two closely related features alongside Fable 5: scheduled agent deployments and a "Dreaming" feature. Scheduled agents let you give a Claude deployment a cron schedule, so it can run nightly data syncs, weekly compliance scans, or daily digests without any human trigger. The Dreaming feature is the more interesting one — between runs, an agent reviews its past sessions, surfaces patterns, and updates its memory store, so it gets meaningfully better at your specific workflows without you retraining anything.',
        'Claude Design also got a major June update timed to the Fable 5 launch. The design tooling now supports importable design systems, real WYSIWYG canvas editing, and a two-way /design-sync with Claude Code. That last piece closes a loop that has been frustrating for teams: you can now make a visual change in Claude Design and have it propagate into the corresponding code file without copy-paste. PDF and PPTX export round out the update, making it usable for stakeholder deliverables rather than just internal prototyping.',
        'Claude Code also shipped meaningful improvements this cycle. Computer use extends to the CLI, so Claude can interact with native applications and user interfaces directly from the terminal — not just web pages in a browser. Auto mode got safety improvements, startup clutter was reduced, and a range of bugs across subagents, WebSearch, and background tasks were fixed. The /config command now has inline help, which sounds minor but meaningfully lowers the onboarding time for new Claude Code users.',
        'For builders the practical question is when to reach for Fable 5 versus Sonnet or Haiku. The pricing is higher, so you do not want to use it for simple tasks. The sweet spot is anything that requires sustained reasoning over a large context — multi-step research pipelines, codebases with hundreds of files, agent workflows that run unattended for hours. For quick single-turn tasks, Sonnet still wins on cost-to-quality ratio.',
        'The scheduled agent and Dreaming features together suggest where Anthropic sees the market going: persistent agents that accumulate institutional memory rather than stateless models you prompt fresh each time. If that bet is right, the developers who win will be the ones who design their agent workflows for continuous improvement from the start, not as an afterthought. Fable 5 gives you the infrastructure for that. The design work is still yours.',
        'Bottom line: Fable 5 is a real upgrade for long-horizon agentic work and large-context tasks. The Claude Design and Claude Code improvements ship across all paid plans. If you are building something that needs to run unattended and get smarter over time, this release gives you a serious new set of tools to work with.',
      ],
    },
    {
      slug: 'chatgpt-mid-2026-model-picker-lockdown-memory',
      title: 'ChatGPT Mid-2026: Model Picker Revamp, Lockdown Mode, and the Memory Overhaul',
      tag: 'news',
      tagLabel: 'News',
      date: '2026-06-19',
      readTime: '8 min',
      excerpt: 'June 2026 delivered three significant ChatGPT changes in one week: a simplified model picker, a new Lockdown security mode, and the biggest memory update since memory launched. Here is the full breakdown.',
      body: [
        'OpenAI has been shipping ChatGPT updates at a pace that makes it hard to keep track of what actually changed. The June 2026 wave is worth pausing on, because three of the updates are substantive: the model picker got a major simplification, a new Lockdown Mode addresses a real security gap, and the memory system received its largest update since the feature launched. Each one reflects a different kind of pressure OpenAI is responding to.',
        'The simplified model picker landed on June 10. Previous versions of ChatGPT required users to manually select from a growing list of GPT variants, which created decision fatigue and support tickets from users confused about which model to pick. The new picker reduces the visible options and automatically routes to the most appropriate model for a given task. It also removed GPT-5.2 model variants — including GPT-5.2 Instant, Thinking, and Pro — from the selection entirely as of June 12, consolidating the lineup around newer and better-performing options.',
        'Lockdown Mode is the most security-forward feature OpenAI has shipped in ChatGPT to date. The mode restricts what ChatGPT can access during a session, disabling memory reads and external tool connections, and is aimed at users who handle sensitive information and want a clean-room conversation environment. Alongside Lockdown, OpenAI shipped Active Sessions — a dashboard showing every logged-in device with details like device type, location, sign-in time, and trusted status, with a one-click sign-out for any session you do not recognize. For professional users, this closes a gap that felt long overdue.',
        'The memory overhaul is the update with the most day-to-day impact for regular users. ChatGPT now shows a memory summary — a human-readable digest of what the system has saved about you — and lets you edit it directly by typing or highlighting text. You can delete individual memories, turn memory off entirely per conversation, or correct things that were remembered inaccurately. Previously, memory was a black box you could only reset entirely. Granular control was the most-requested feature from power users, and it is now live.',
        'On the capability side, ChatGPT added pronunciation guidance for more than 60 languages, which sounds niche but matters enormously for language learning and accessibility use cases. The World Cup integration is more of a timely feature — ChatGPT can now discuss schedules, matchups, team rosters, and predictions conversationally, which is the kind of topical context injection that makes a general assistant feel relevant during a major event rather than out of touch.',
        'Mobile improvements shipped alongside the desktop updates. Photo capture on iOS is noticeably faster. Android paid plan users can long-press the send button to switch models for a single message without changing their default — a small quality-of-life improvement that heavy users will appreciate. These are the kinds of friction reductions that do not make headlines but compound into a meaningfully better daily experience.',
        'The overall trajectory of these June updates is toward professional-grade reliability rather than headline-grabbing new capabilities. Lockdown Mode and Active Sessions are about trust. The memory controls are about correctness. The model picker simplification is about reducing cognitive load. OpenAI is clearly responding to enterprise feedback: the users most likely to pay premium prices want control, transparency, and security more than they want new gimmicks.',
        'If you use ChatGPT daily, the memory summary is worth reviewing immediately — it is probably more detailed than you expect. And if you work with sensitive information, Lockdown Mode is worth understanding before you need it. The June 2026 update is quietly one of the more important ChatGPT releases of the year.',
      ],
    },
    {
      slug: 'gemini-35-flash-default-google-io-2026',
      title: 'Gemini 3.5 Flash Is Now Default — And It Comes With Omni, Spark, and a New Daily Brief',
      tag: 'news',
      tagLabel: 'News',
      date: '2026-06-18',
      readTime: '8 min',
      excerpt: 'Google made Gemini 3.5 Flash the default model for all enterprise users on June 9 — and that is just one of a half-dozen Gemini changes that shipped in and around Google I/O 2026. Here is the full picture.',
      body: [
        'Google I/O 2026 was the biggest AI product announcement event Google has run since the original Gemini launch. The headline coming out of it was not a single model or feature — it was the density of shipping: Gemini 3.5 Flash as a universal default, Gemini Omni for video creation, a personal AI agent called Gemini Spark, a Daily Brief feature, deeper Chrome integration, and new Pixel device capabilities. Taken together, they represent Google trying to close the gap with both OpenAI and Anthropic on multiple fronts simultaneously.',
        'Gemini 3.5 Flash becoming the default model for all Gemini Enterprise users on June 9 is significant because it is not optional — it is enabled by default and cannot be disabled at the org level. That is a strong signal of confidence from Google. Flash has been the cost-efficient variant of the Gemini 3 family, but 3.5 is performant enough that Google is comfortable making it the floor rather than the ceiling for enterprise deployments. Early benchmarks show meaningful improvements in code generation, multilingual tasks, and structured output consistency compared to Gemini 3.0.',
        'Gemini Omni is the video creation model that was shown at I/O 2026 and is rolling out through the Gemini app. It takes text, images, audio, and video as inputs and produces video as output, bringing Google into direct competition with runway-style generative video tools but with Gemini\'s multimodal reasoning as the differentiator. The demo use cases shown at I/O included product advertisements from a single product photo, explainer videos from a slide deck, and music video generation from lyrics — all from the Gemini interface.',
        'Gemini Spark is Google\'s answer to the "personal AI agent" use case. It is a persistent, personalized agent layer inside the Gemini app that learns your preferences, schedules, and working patterns over time. The positioning is explicitly as a personal executive assistant rather than a general chatbot — it tracks your calendar, surfaces relevant information before meetings, and proactively surfaces tasks that need attention rather than waiting to be asked. This puts Google directly in competition with the scheduled agent features that Anthropic shipped in the same month.',
        'The Daily Brief feature is part of the Gemini app redesign that also shipped at I/O. Each morning, the app delivers a structured briefing personalized to your interests, ongoing projects, and scheduled events. It is similar to AI newsletter digests that third-party tools have offered, but native to the Gemini app and generated from your actual Google data — Calendar, Gmail, Drive — rather than just news feeds. The redesigned interface makes this the first thing you see when you open the app, signaling that Google wants Gemini to be the starting point for your day rather than a tab you open when you have a specific question.',
        'Chrome on Android is getting Gemini integration in late June, initially for English-US devices with 4GB of RAM or more. The integration includes Nano Banana (Google\'s on-device small model) and auto-browse, which can summarize articles, answer questions about page content, and provide detailed explanations without leaving the browser. The value proposition is clear: the same kind of sidebar AI that Microsoft built into Edge, but powered by Gemini and running partly on-device for privacy.',
        'For the Pixel hardware side, the June Pixel Drop added Gemini-powered video creation, original music track generation, and enhanced photo editing. These are consumer-facing features rather than developer capabilities, but they matter because they put multimodal AI generation in the hands of anyone who owns a modern Pixel device — without requiring a subscription or a separate app.',
        'Google is playing a broader game than any single model release. The I/O 2026 wave of Gemini updates covers enterprise defaults, personal agents, video generation, browser integration, and hardware features simultaneously. Whether they can execute all of it at quality is the open question — Google has a history of shipping compelling demos that take longer than expected to mature. But the ambition and breadth are real, and any builder who dismissed Gemini a year ago should be paying closer attention now.',
      ],
    },
    {
      slug: 'openai-codex-2026-agentic-coding-4m-developers',
      title: 'OpenAI Codex 2026: 4 Million Weekly Developers and the Rise of the Agentic Coding Stack',
      tag: 'deep-dive',
      tagLabel: 'Deep Dive',
      date: '2026-06-17',
      readTime: '10 min',
      excerpt: 'OpenAI Codex hit 4 million weekly active developers by April 2026, earned a Gartner Leaders quadrant position, and shipped a security agent, multi-agent architecture, and standalone web search. Here is the complete state of Codex in mid-2026.',
      body: [
        'When OpenAI relaunched Codex as a coding agent in 2025, it was positioned as a developer productivity tool — a smarter autocomplete. By mid-2026 that framing has been replaced by something more ambitious: Codex is now being marketed as an agentic coding platform, and the product has the metrics and enterprise recognition to back the claim. Four million weekly active developers as of the GPT-5.5 launch in April 2026. A spot in the Gartner Magic Quadrant for Enterprise AI Coding Agents. A security-focused sub-agent. A multi-agent architecture. These are not incremental updates to a code autocomplete tool.',
        'The move to GPT-5.5 as the underlying model was the most significant infrastructure change in the 2026 Codex updates. GPT-5.5 is OpenAI\'s agentic-first base model — designed for sustained reasoning across long tasks rather than optimized for single-turn response quality. For Codex, that translates to better performance on refactors spanning hundreds of files, multi-step debugging sessions that require tracking context across multiple tool calls, and code generation tasks where the correct output depends on understanding the full architecture rather than the immediate context window.',
        'The multi-agent architecture is now generally available. A Codex manager agent can coordinate several parallel worker agents, each with its own context and specialization. In practice this means you can assign a task like "migrate this codebase from Python 2 to Python 3 and write tests for every changed function" and have multiple agents work on separate modules in parallel, with the manager reconciling conflicts and tracking completion. The time savings on large-scale refactors are substantial — early case studies from enterprise users showed 60-70% reductions in calendar time for tasks that would previously have taken a senior engineer a week.',
        'Codex Security shipped in March 2026 as a specialized sub-agent focused on application security. It runs static analysis, identifies CVEs in dependencies, finds common vulnerability patterns (injection, XSS, SSRF), and generates remediation code rather than just flagging issues. The integration with the main Codex workflow is tight: you can trigger a security scan on any codebase and get prioritized, actionable output with code patches ready to apply. For security-conscious engineering teams, this reduces the cycle time from "vulnerability discovered" to "patch in production" significantly.',
        'Token-based billing, which launched in April 2026, changed the economics of using Codex for large tasks. The previous credit model made it hard to predict costs for complex multi-step jobs. Token billing — input tokens at the base rate, cached input at roughly a tenth of that, output tokens at the output rate — is more predictable and rewards efficient prompt design. Teams that use Codex heavily report that cached context is the biggest lever for cost control: structuring tasks so that the codebase context is cached rather than re-sent on every call can cut costs dramatically on large-scale operations.',
        'The June 2026 improvements added standalone web search in Code mode, richer MCP schema support, more detailed codex doctor diagnostic reports, and faster plugin marketplace listings. The MCP schema support is particularly relevant for builders using Codex as part of a larger agentic stack — Codex can now correctly describe and consume complex tool schemas, which reduces hallucinated tool calls and improves reliability when integrating with custom MCP servers.',
        'Platform availability expanded in March 2026 when the Codex desktop app launched on Windows, completing the cross-platform story alongside macOS. The app is designed for managing multiple agents simultaneously and supervising long-running work — less like an IDE and more like a project management tool where your workers happen to be AI agents. VS Code, Cursor, and Windsurf integrations remain available for developers who prefer to stay in their editor.',
        'The Gartner recognition matters because it signals enterprise procurement legitimacy. Engineering org leaders who need to justify a tool purchase to a CTO or a security team have a cleaner path when the vendor appears in the Leaders quadrant. For OpenAI, which has historically been stronger with individual developers than with enterprise procurement processes, this is a meaningful shift in positioning. The 4 million weekly developer number and Gartner recognition together suggest Codex has crossed the chasm from developer tool to enterprise platform. How well it holds that position as Google Antigravity 2.0 and other competitors scale up will be the defining competition of the next 12 months.',
      ],
    },
    {
      slug: 'google-antigravity-20-agentic-ide-io-2026',
      title: 'Google Antigravity 2.0: The AI IDE That Plans, Codes, Tests, and Deploys From One Prompt',
      tag: 'deep-dive',
      tagLabel: 'Deep Dive',
      date: '2026-06-16',
      readTime: '9 min',
      excerpt: 'Google launched Antigravity 2.0 at I/O 2026 with a CLI, SDK, subagent orchestration, and an AI Ultra plan. It is the most complete AI development platform Google has shipped — and it is targeting the same market as Codex, Cursor, and Claude Code.',
      body: [
        'Google shipped Antigravity 2.0 at I/O 2026 on May 19, and the developer community has spent the past month catching up to what it actually is. Antigravity is not a chatbot with a code editor bolted on. It is an agent-first development platform that can take a natural language prompt describing an application, generate a plan, write the code, run tests, and deploy — all without manual intervention. The 2.0 launch added a CLI, a full SDK for custom workflows, and an updated desktop app for macOS and Windows. Powered by Gemini 3.5 Flash, it positions Google directly against OpenAI Codex, Anthropic Claude Code, and the Cursor/Windsurf editor ecosystem.',
        'The core Antigravity model is Gemini 3.5 Flash running in what Google calls "agent-first mode." The distinction from standard Gemini usage is that Antigravity maintains persistent project state across sessions, can trigger tool use sequences autonomously, and is explicitly designed for multi-step development workflows rather than single-turn code generation. When you describe an application, Antigravity generates a structured plan with dependencies, estimated complexity, and a step-by-step build order before writing a single line of code. That planning layer is what separates it from simple "generate this function" tooling.',
        'Subagent orchestration is one of the 2.0 headline features. You can define specialized subagents for specific tasks — a test writer, a documentation generator, a security scanner — and have a coordinator agent route work to them based on what is happening in the build. The coordinator manages dependencies between subagents and resolves conflicts when outputs from different agents need to be integrated. For complex application builds, this parallelization can dramatically reduce time to first working build. Google showed a demo at I/O where a full-stack web application with authentication, database schema, and API layer was built and deployed in under 20 minutes from a single prompt.',
        'The CLI is the feature that separates the 2.0 release from 1.0 most practically. Antigravity\'s original desktop-only interface was powerful but isolated from existing development workflows. The CLI brings Antigravity into terminal-based workflows, CI/CD pipelines, and scripts, making it composable with the rest of a developer\'s toolchain. You can trigger Antigravity agents from a Makefile, chain them with shell scripts, or integrate them into a GitHub Actions workflow. The SDK extends this further by exposing the Antigravity agent architecture programmatically, so teams can build custom tooling on top of the platform.',
        'The $100/month AI Ultra plan is Google\'s premium tier for Antigravity and broader Google AI services. It includes higher rate limits on Gemini 3.5 Flash, priority access to Gemini Omni for video generation, and early access to new Antigravity features. For professional developers and small teams that use AI tooling heavily, $100/month is competitive with comparable tiers from OpenAI and Anthropic. For individuals doing occasional use, the free tier with Gemini 3.5 Flash provides meaningful capability without a subscription.',
        'Google\'s positioning for Antigravity is explicitly at startup founders and indie developers, not just enterprise engineering teams. The I/O 2026 messaging emphasized the ability to build a production-ready application without a large team — Antigravity as a force multiplier that lets a solo founder move at the pace of a small team. That positioning aligns with the free tier strategy: get developers hooked on the workflow, then convert them as their usage and revenue scale up.',
        'The competitive landscape for agentic coding tools is now genuinely crowded. Codex has the enterprise recognition and 4 million weekly users. Claude Code has deep integration with the Claude ecosystem and Anthropic\'s safety focus. Cursor and Windsurf have large existing user bases from the editor side. Antigravity 2.0 is the new entrant with the most integrated deployment story — it is the only tool where planning, building, testing, and deploying are first-class capabilities in a single product rather than requiring integration work.',
        'Whether Antigravity can convert Google I/O buzz into sustained developer adoption is the open question. Google\'s track record on developer tools has been mixed — products that launch impressively and then fail to iterate fast enough. But 2.0 is a more complete product than 1.0 was, the CLI and SDK changes make it genuinely composable, and Gemini 3.5 Flash is a strong base model for code generation tasks. If you have not tried it yet, the free tier makes the barrier to entry essentially zero. That is worth an afternoon to evaluate.',
      ],
    },
    {
      slug: 'prompt-to-47-dollar-product',
      title: 'How I Packaged a Prompt into a $47 Product in 48 Hours',
      tag: 'build-log',
      tagLabel: 'Build Log',
      date: '2026-06-14',
      readTime: '7 min',
      excerpt: 'A real-time case study walking through every step of turning a raw prompt into a productized, shippable asset with pricing, copy, and delivery.',
      body: [
        'I had a prompt I used every day to turn meeting notes into action items. It was good. But a good prompt is not a product.',
        'Over 48 hours I packaged it: named the outcome, defined the buyer, wrote the promise, set a price, and built a one-page delivery. Here is exactly what I did.',
        'Step one was naming the outcome, not the mechanism. Nobody buys "a prompt." They buy "meeting notes to action items in 30 seconds." That reframe changed everything about the copy.',
        'By hour 48 it was live at $47. The lesson: the prompt was 10% of the work. Packaging was the product.',
      ],
    },
    {
      slug: 'mcp-server-setup-guide',
      title: 'The MCP Server Setup Guide Nobody Wrote',
      tag: 'tutorial',
      tagLabel: 'Tutorial',
      date: '2026-06-09',
      readTime: '11 min',
      excerpt: 'Everything you need to know to set up, configure, and connect an MCP server to Claude — without the gaps the official docs leave behind.',
      body: [
        'MCP is powerful but the setup docs assume a lot. This guide fills the gaps that trip up most first-timers.',
        'We cover the config file location, environment variables, the most common connection errors, and how to verify the server is actually exposing its tools.',
        'The single biggest gotcha: restarting the client. Config changes do not hot-reload. Restart fully.',
        'By the end you will have a working server and know how to debug the next one yourself.',
      ],
    },
    {
      slug: 'claude-skills-vs-plugins',
      title: 'Claude Skills vs Plugins: A Practical Breakdown',
      tag: 'deep-dive',
      tagLabel: 'Deep Dive',
      date: '2026-06-03',
      readTime: '9 min',
      excerpt: 'An honest comparison of Claude skills and plugins — what they do, where they overlap, and when to use each one in your AI system stack.',
      body: [
        'Skills and plugins solve related but different problems. Confusing them leads to over-engineering.',
        'A skill is reusable knowledge and instructions. A plugin bundles skills, commands, and configuration for distribution.',
        'Rule of thumb: start with a skill. Reach for a plugin only when you need to package and share several skills together.',
        'We walk through three real scenarios and pick the right tool for each.',
      ],
    },
    {
      slug: 'tested-this-tool-n8n',
      title: 'I Tested n8n for AI Automation for 30 Days',
      tag: 'tested',
      tagLabel: 'I Tested This',
      date: '2026-05-26',
      readTime: '8 min',
      excerpt: 'Thirty days of building AI automations in n8n — what worked, what broke, and whether it is worth replacing Zapier for solo builders.',
      body: [
        'I moved my automations from Zapier to n8n for a month. Here is the honest report.',
        'The wins: self-hosting, no per-task pricing, and real branching logic. The pain: a steeper learning curve and occasional node quirks.',
        'For high-volume AI workflows, n8n paid for itself in week one. For simple two-step zaps, it was overkill.',
        'Verdict: worth it if you are running more than a handful of automations.',
      ],
    },
    {
      slug: 'turn-this-into-a-product',
      title: 'Turn This Into a Product: The Repurposing Playbook',
      tag: 'build-log',
      tagLabel: 'Build Log',
      date: '2026-05-18',
      readTime: '6 min',
      excerpt: 'A repeatable playbook for spotting which of your workflows can become a sellable product — and which should stay internal tools.',
      body: [
        'Not every workflow should be a product. This playbook helps you tell the difference.',
        'The test: does it solve an expensive, repeated, painful problem for someone other than you? If yes, productize. If no, keep it as an internal tool.',
        'We score three of my own workflows against the test and decide which one ships.',
      ],
    },
    {
      slug: 'claude-code-on-the-web',
      title: 'A Practical Guide to Claude Code on the Web',
      tag: 'tutorial',
      tagLabel: 'Tutorial',
      date: '2026-05-11',
      readTime: '10 min',
      excerpt: 'How to set up a repo for Claude Code on the web, run sessions in the cloud, and ship changes through pull requests.',
      body: [
        'Claude Code on the web runs in an ephemeral cloud container. That changes how you set up a repo.',
        'The key: a SessionStart hook that installs dependencies and verifies tests run, so every session starts ready.',
        'We walk through configuring the environment, network policy, and the PR-based workflow.',
      ],
    },
  ];

  /* ─── Shop products ─────────────────────────────────────── */
  const products = [
    {
      id: 'prompt-pack-pro',
      title: 'Prompt Pack Pro',
      kind: 'Prompt Pack',
      price: 29,
      desc: '50 battle-tested prompts for coding, content, and research — organized and tagged.',
      features: ['50 prompts', 'Notion database included', 'Lifetime updates'],
      badge: 'Bestseller',
    },
    {
      id: 'skill-pack-builder',
      title: 'Claude Skill Pack',
      kind: 'Skill Pack',
      price: 49,
      desc: 'Ten ready-to-install Claude skills for common solopreneur workflows.',
      features: ['10 SKILL.md files', 'Install guide', 'Compatible with Claude Code'],
      badge: null,
    },
    {
      id: 'agent-starter-kit',
      title: 'Agent Starter Kit',
      kind: 'Starter Kit',
      price: 79,
      desc: 'Everything to ship your first multi-agent system — structure, manifests, and router.',
      features: ['Agent pack template', 'Router boilerplate', 'Video walkthrough'],
      badge: null,
    },
    {
      id: 'mcp-starter-kit',
      title: 'MCP Starter Kit',
      kind: 'Starter Kit',
      price: 59,
      desc: 'Scaffold, test, and ship your first MCP server with confidence.',
      features: ['Server boilerplate', 'Spec generator access', 'Debugging checklist'],
      badge: 'New',
    },
    {
      id: 'notion-template-bundle',
      title: 'Notion Template Bundle',
      kind: 'Templates',
      price: 19,
      desc: 'The prompt database, build tracker, and product pipeline — all in one bundle.',
      features: ['3 Notion templates', 'Setup video', 'Lifetime updates'],
      badge: null,
    },
    {
      id: 'build-audit',
      title: 'Build Audit (Done For You)',
      kind: 'Service',
      price: 199,
      desc: 'I personally audit your AI build and deliver a prioritized fix list within 5 days.',
      features: ['Full build review', 'Prioritized fix list', '30-min call'],
      badge: 'Service',
    },
    {
      id: 'free-starter-pack',
      title: 'AI Builder Starter Pack',
      kind: 'Free Download',
      price: 0,
      desc: '5 prompts, a build checklist, and the glossary — the fastest way to start.',
      features: ['5 prompts', 'Build checklist PDF', 'Glossary PDF'],
      badge: 'Free',
    },
    {
      id: 'claude-build-kit',
      title: 'Claude Build Kit',
      kind: 'Build Kit',
      price: 39,
      desc: 'Skills, CLAUDE.md templates, and hooks to set up a serious Claude Code workflow fast.',
      features: ['5 skill templates', 'CLAUDE.md starter set', 'Pre-commit hook included'],
      badge: null,
    },
    {
      id: 'ai-systems-mini-course',
      title: 'AI Systems Mini Course',
      kind: 'Mini Course',
      price: 89,
      desc: '12 lessons walking the full pipeline from prompt to shipped product.',
      features: ['12 video lessons', 'Prompt-to-product templates', 'Lifetime access'],
      badge: null,
    },
    {
      id: 'custom-workflow-build',
      title: 'Custom Workflow Build (Done For You)',
      kind: 'Service',
      price: 349,
      desc: 'I design and build a custom automation workflow for your business, end to end.',
      features: ['1:1 scoping call', 'Custom-built workflow', '2 weeks of support'],
      badge: 'Service',
    },
    {
      id: 'saat-template-pack',
      title: 'SaaT Template Pack',
      kind: 'Templates',
      price: 45,
      desc: '3 internal-tool dashboard templates for turning a workflow into a small Software-as-a-Tool.',
      features: ['3 dashboard templates', 'Data model examples', 'Setup guide'],
      badge: null,
    },
  ];

  /* ─── Changelog entries ─────────────────────────────────── */
  const changelog = [
    {
      date: '2026-07-15',
      version: 'v0.5',
      type: 'added',
      title: 'Library expansion & trust system',
      items: ['14 new library assets across 14 new categories', 'Trust & quality data on every asset (risk, rating, limitations, requirements)', 'Tool / use case / status / license filters', '4 new tools, 2 new learning paths, 5 new shop products'],
    },
    {
      date: '2026-06-18',
      version: 'v0.4',
      type: 'added',
      title: 'Multi-page site launch',
      items: ['Full Tools, Library, Blog, Shop, and Build Studio pages', 'Working library search and filters', 'Asset detail pages'],
    },
    {
      date: '2026-06-14',
      version: 'v0.3',
      type: 'added',
      title: 'Build Log goes live',
      items: ['First case study published', 'Blog post detail pages', 'New tag system'],
    },
    {
      date: '2026-06-10',
      version: 'v0.2',
      type: 'updated',
      title: 'Library assets refreshed',
      items: ['Claude Code System Prompt updated to v2.1', 'GitHub MCP Server retested', 'Compatibility data added'],
    },
    {
      date: '2026-06-01',
      version: 'v0.1',
      type: 'added',
      title: 'AISolutionsOS prototype',
      items: ['Landing page', 'Tool previews', 'Initial library structure'],
    },
  ];

  /* ─── Glossary ──────────────────────────────────────────── */
  const glossary = [
    { term: 'MCP', full: 'Model Context Protocol', def: 'An open standard that lets AI tools connect to external systems through servers exposing tools and resources.' },
    { term: 'CLI', full: 'Command-Line Interface', def: 'A text-based program you run in a terminal by typing commands and flags.' },
    { term: 'Agent', full: 'AI Agent', def: 'An AI system that can take actions — calling tools, reading files, running steps — toward a goal, not just answering once.' },
    { term: 'Subagent', full: 'Subagent', def: 'A specialized agent spawned by a parent agent to handle a focused part of a larger task.' },
    { term: 'Hook', full: 'Hook', def: 'A script the harness runs automatically at a defined moment (e.g. session start, before a tool call).' },
    { term: 'Skill', full: 'Skill', def: 'Reusable instructions and knowledge an AI tool can load on demand to perform a specific kind of task.' },
    { term: 'Plugin', full: 'Plugin', def: 'A distributable bundle of skills, commands, and configuration that extends an AI tool.' },
    { term: 'AGENTS.md', full: 'AGENTS.md', def: 'A repo file giving coding agents project-specific instructions and conventions.' },
    { term: 'CLAUDE.md', full: 'CLAUDE.md', def: 'Claude Code’s project memory file — conventions, commands, and context loaded each session.' },
    { term: 'GEMINI.md', full: 'GEMINI.md', def: 'Gemini CLI’s project context file — conventions, commands, and context loaded each session, parallel to CLAUDE.md.' },
    { term: 'SaaT', full: 'Software as a Tool', def: 'A small, focused internal tool that does one job well — often the seed of a future product.' },
    { term: 'Workflow', full: 'Workflow', def: 'A defined sequence of steps to accomplish a repeatable task.' },
    { term: 'Automation', full: 'Automation', def: 'A workflow that runs without manual steps, usually triggered by an event or schedule.' },
    { term: 'Prompt Pack', full: 'Prompt Pack', def: 'A curated, organized collection of prompts sold or shared as a unit.' },
    { term: 'Context File', full: 'Context File', def: 'A file (like CLAUDE.md) that supplies persistent background an AI tool reads automatically.' },
    { term: 'Tool Call', full: 'Tool Call', def: 'When an AI model invokes an external function or tool to get information or take an action.' },
    { term: 'RAG', full: 'Retrieval-Augmented Generation', def: 'A technique where relevant documents are retrieved and fed to the model to ground its answers.' },
  ];

  /* ─── Learning paths ────────────────────────────────────── */
  const paths = [
    { id: 'beginner', title: 'Beginner AI Builder Path', steps: 5, desc: 'Start from zero. Learn prompts, tools, and your first reusable asset.', color: 'blue' },
    { id: 'prompt-to-product', title: 'Prompt-to-Product Path', steps: 6, desc: 'Turn a prompt you already use into a packaged, sellable product.', color: 'purple' },
    { id: 'skill-builder', title: 'Claude Skill Builder Path', steps: 4, desc: 'Go from a manual workflow to a clean, installable Claude skill.', color: 'cyan' },
    { id: 'mcp-builder', title: 'MCP Server Builder Path', steps: 5, desc: 'Spec, scaffold, test, and ship your first MCP server.', color: 'blue' },
    { id: 'monetization', title: 'AI Creator Monetization Path', steps: 7, desc: 'Build a small catalog of paid assets and a simple shop.', color: 'purple' },
    { id: 'automation', title: 'Solopreneur Automation Path', steps: 6, desc: 'Automate the repetitive parts of running a one-person business.', color: 'cyan' },
    { id: 'content-engine', title: 'Content Engine Path', steps: 5, desc: 'Build a repeatable pipeline from raw idea to published, repurposed content.', color: 'blue' },
    { id: 'saat-builder', title: 'Internal SaaT Builder Path', steps: 6, desc: 'Turn one internal workflow into a small Software-as-a-Tool you actually use.', color: 'purple' },
  ];

  /* ─── Compatibility matrix ──────────────────────────────── */
  const compatTools = ['ChatGPT', 'Claude', 'Claude Code', 'Codex', 'Gemini', 'Gemini CLI', 'Antigravity', 'Cursor', 'GitHub', 'Vercel', 'Notion', 'Google Drive', 'n8n', 'Zapier', 'Make', 'Airtable', 'Supabase'];

  /* ─── Site-wide nav definition (single source of truth) ──── */
  const nav = [
    { label: 'Home', href: 'index.html' },
    { label: 'Tools', href: 'tools.html' },
    { label: 'AI Library', href: 'library.html' },
    { label: 'Blog', href: 'blog.html' },
    { label: 'Build Studio', href: 'build-studio.html' },
    { label: 'Shop', href: 'shop.html' },
    { label: 'Changelog', href: 'changelog.html' },
  ];

  window.AISO = {
    tools: tools,
    library: library,
    posts: posts,
    products: products,
    changelog: changelog,
    glossary: glossary,
    paths: paths,
    compatTools: compatTools,
    nav: nav,

    /* Lookup helpers */
    getTool: function (id) { return tools.find(function (t) { return t.id === id; }); },
    getAsset: function (id) { return library.find(function (a) { return a.id === id; }); },
    getPost: function (slug) { return posts.find(function (p) { return p.slug === slug; }); },
    getProduct: function (id) { return products.find(function (p) { return p.id === id; }); },
  };
})();
